/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DBusAdaptor -p qibusdbusadaptor org.freedesktop.DBus.xml org.freedesktop.DBus
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "qibusdbusadaptor.h"

/*
 * Implementation of interface class DBusAdaptor
 */

DBusAdaptor::DBusAdaptor(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DBusAdaptor::~DBusAdaptor()
{
}

